export const metadata = {
  title: "Not Found || Pucu - Nextjs Portfolio Template",
  description: "Generated by create next app",
};

export default function NotFoundLayout({ children }) {
  return <section>{children}</section>;
}
